### ISSUE TITLE
Internal Server Error when accessing port 8858

### ISSUE THREAD

**Issue by JahedulAnowar** [bbc/nmos-device-connection-management-ri#26]
I tried to run the connection management,
`$ connectionmanagement`
````
WARNING:mdnsbridge:This class is deprecated. Please use the matching one in nmos-mdns-bridge instead.
DEBUG:utils:Choosing interface from /etc/nmoscommon/config.json file: []
DEBUG:utils:Could not find ipp-utils, will try using default gateway interface
DEBUG:utils:Choosing interface using the default gateway: 163.138.145.16
WARNING:conmanage:Could not find ipppython facade
DEBUG:conmanage:Running Connection Management Service
DEBUG:conmanage:Waiting for httpserver to start...
HttpServer running
DEBUG:conmanage:Running on port: 8856
INFO:facade_proxy:Register service
DEBUG:conmanage:Waiting for httpserver to start...
DEBUG:utils:Choosing interface from /etc/nmoscommon/config.json file: []
DEBUG:utils:Could not find ipp-utils, will try using default gateway interface
DEBUG:utils:Choosing interface using the default gateway: 163.138.145.16
DEBUG:utils:Choosing interface from /etc/nmoscommon/config.json file: []
DEBUG:utils:Could not find ipp-utils, will try using default gateway interface
DEBUG:utils:Choosing interface using the default gateway: 163.138.145.16
HttpServer running
DEBUG:conmanage:Mock driver interface running on port: 8858
````
No when i try to open port 8858, i get the following error:

```
ERROR:nmoscommon.webapi:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask_Sockets-0.2.1-py3.6.egg/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-0.16.1-py3.6.egg/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/flask_cors.py", line 46, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/webapi.py", line 214, in decorated_function
    r = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/connectionmanagement-2.2.8-py3.6.egg/nmosconnection/nmosDriver.py", line 86, in __index
    return send_file('{}/index.html'.format(self.path))
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/connectionManagementDriver/index.html'
ERROR:nmoscommon.webapi:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask_Sockets-0.2.1-py3.6.egg/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-0.16.1-py3.6.egg/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/flask_cors.py", line 46, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/webapi.py", line 214, in decorated_function
    r = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/connectionmanagement-2.2.8-py3.6.egg/nmosconnection/nmosDriver.py", line 86, in __index
    return send_file('{}/index.html'.format(self.path))
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/connectionManagementDriver/index.html'
ERROR:nmoscommon.webapi:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask_Sockets-0.2.1-py3.6.egg/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-0.16.1-py3.6.egg/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/flask_cors.py", line 46, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/webapi.py", line 214, in decorated_function
    r = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/connectionmanagement-2.2.8-py3.6.egg/nmosconnection/nmosDriver.py", line 86, in __index
    return send_file('{}/index.html'.format(self.path))
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/connectionManagementDriver/index.html'
^CERROR:facade_proxy:Exception when unregistering service: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/ipc.py", line 96, in _run
    r = self.methods[msg['function']](*(msg['args']), **(msg['kwargs']))
  File "/usr/local/lib/python3.6/dist-packages/nodefacade-0.12.2-py3.6.egg/nmosnode/serviceinterface.py", line 70, in srv_unregister
    return self.registry.unregister_service(name, pid)
  File "/usr/local/lib/python3.6/dist-packages/nodefacade-0.12.2-py3.6.egg/nmosnode/registry.py", line 151, in unregister_service
    for key in self.services[name][namespace][type].keys():
RuntimeError: dictionary changed size during iteration

ERROR:facade_proxy:Exception when unregistering service: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nmoscommon/ipc.py", line 96, in _run
    r = self.methods[msg['function']](*(msg['args']), **(msg['kwargs']))
  File "/usr/local/lib/python3.6/dist-packages/nodefacade-0.12.2-py3.6.egg/nmosnode/serviceinterface.py", line 70, in srv_unregister
    return self.registry.unregister_service(name, pid)
  File "/usr/local/lib/python3.6/dist-packages/nodefacade-0.12.2-py3.6.egg/nmosnode/registry.py", line 151, in unregister_service
    for key in self.services[name][namespace][type].keys():
RuntimeError: dictionary changed size during iteration
```
Am i missing some dependencies?

**Comment by andrewbonney** [comment]
It looks as though the 404 errors may be caused by some missing files in /var/www. I don't think these will get installed by the Python packaging, so you may need to manually copy the files from https://github.com/bbc/nmos-device-connection-management-ri/tree/master/var/www into that directory.

**Comment by JahedulAnowar** [comment]
I checked the directories and found that all of the files seem to be exactly where they were supposed to be. Just for the sake of confirmation i copied the files again, but still the error is there.
Any suggestions?

**Comment by andrewbonney** [comment]
I'm afraid I'm not sure. The error message does seem to be quite explicit, so I would expect `/var/www/connectionManagementDriver/index.html` to be missing. It could be a permissions issue if the program is being run as a different user to one who has permission to access the file, but I would have expected a different error in that case.

The second set of errors relate to the fact that an 'nmosnode' service doesn't seem to be running, but this shouldn't be a problem as you can run without it. Those errors only appear to be triggered because of the missing file.

**Comment by JahedulAnowar** [comment]
Sorry, previously i wasn't actually looking at local /var/www directory also there was the permission issue.  
It's working now.
Thank you for helping.

**Comment by andrewbonney** [comment]
No problem. Glad it's sorted.
